
version: '3.7'

services:
  gameapp-database:
    image: mysql:8.0
    container_name: gameapp-database
    restart: always
    ports:
      - "5510:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: gameappRoo7t0lk2o20
      MYSQL_DATABASE: gameapp_db
      MYSQL_USER: gameapp
      MYSQL_PASSWORD: gameappt0lk2o20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gameapp-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: gameapp-database
      PMA_PORT: 3306   # ✅ پورت داخلی MySQL
    depends_on:
      - gameapp-database

volumes:
  dbdata:
